name: Build and Release D-deskcal

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0, v1.2.3)
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.14.1
        pip install pyinstaller-hooks-contrib
        pip install -r requirements.txt
        pip freeze > freeze_ci.txt
    
    - name: Verify icon file exists
      run: |
        if (Test-Path "icons/tray_icon.ico") {
          Write-Host "✅ Icon file found: icons/tray_icon.ico"
        } else {
          Write-Host "❌ Icon file missing: icons/tray_icon.ico"
          exit 1
        }
    
    - name: Build application
      run: |
        python build_script.py
    
    - name: Verify build output
      run: |
        if (Test-Path "dist/D-deskcal") {
          Write-Host "✅ Build successful: dist/D-deskcal"
          Get-ChildItem -Path "dist/D-deskcal" -Recurse | Select-Object Name, Length
        } else {
          Write-Host "❌ Build failed: dist/D-deskcal not found"
          exit 1
        }
    
    - name: Create installer package
      run: |
        $version = Get-Content -Path "VERSION" -Raw
        $version = $version.Trim()
        
        # Create installer zip
        $installerName = "D-deskcal-v$version-installer.zip"
        
        # Compress the built application
        Compress-Archive -Path "dist/D-deskcal/*" -DestinationPath "dist/$installerName" -Force
        
        Write-Host "✅ Created installer: $installerName"
        
        # Verify installer
        if (Test-Path "dist/$installerName") {
          $size = (Get-Item "dist/$installerName").Length / 1MB
          Write-Host "📦 Installer size: $([math]::Round($size, 2)) MB"
        }
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: D-deskcal-build
        path: |
          dist/D-deskcal-v*-installer.zip
          dist/D-deskcal/
          freeze_ci.txt
          build/*.toc
          build/*.txt
    
    - name: Get version
      id: version
      run: |
        $version = Get-Content -Path "VERSION" -Raw
        $version = $version.Trim()
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        echo "TAG_NAME=v$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    
    - name: Create portable zip
      run: |
        $version = "${{ steps.version.outputs.VERSION }}"
        $portableName = "D-deskcal-v$version-portable.zip"
        
        # Create portable zip with all necessary files (same as installer but different name)
        Compress-Archive -Path "dist/D-deskcal/*" -DestinationPath "dist/$portableName" -Force
        
        Write-Host "✅ Created portable: $portableName"
        
        # Verify portable file
        if (Test-Path "dist/$portableName") {
          $size = (Get-Item "dist/$portableName").Length / 1MB
          Write-Host "📦 Portable size: $([math]::Round($size, 2)) MB"
        }
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $version = "${{ steps.version.outputs.VERSION }}"
        $tagName = "${{ steps.version.outputs.TAG_NAME }}"
        
        $releaseBody = @"
        ## D-deskcal v$version
        
        ### 📦 Downloads
        - **Installer**: D-deskcal-v$version-installer.zip
        - **Portable**: D-deskcal-v$version-portable.zip
        
        ### 🚀 Features
        - Desktop calendar widget with Google Calendar integration
        - System tray integration  
        - Local-first data storage
        - Auto-update functionality
        
        ### 📋 Installation
        1. Download the installer zip file
        2. Extract to your desired location
        3. Run ``D-deskcal.exe``
        4. Configure your Google Calendar (optional)
        
        ### ⚙️ System Requirements
        - Windows 10/11
        - Internet connection (for Google Calendar sync)
        
        ### 🔄 Auto-Update
        This version includes automatic update checking. The application will notify you when new updates are available.
        
        ---
        
        **Full Changelog**: https://github.com/thejurio/D-deskcal/commits/$tagName
        "@
        
        gh release create "$tagName" "dist/D-deskcal-v$version-installer.zip" "dist/D-deskcal-v$version-portable.zip" --title "D-deskcal v$version" --notes "$releaseBody"
    

  notify-completion:
    needs: build-windows
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Build Success Notification
      run: |
        echo "🎉 D-deskcal build and release completed successfully!"
        echo "📦 Release available at: https://github.com/thejurio/D-deskcal/releases/latest"